name: flutter_background_geolocation
description: The most sophisticated background location tracking & geofencing module with battery-conscious motion-detection intelligence for iOS and Android.
version: 4.13.4
homepage: https://github.com/transistorsoft/flutter_background_geolocation
publish_to: 'none' 

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  background_fetch:
    git:
      url: https://github.com/transistorsoft/flutter_background_fetch.git

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: TSBackgroundGeolocationPlugin
      # android:
      #   package: com.transistorsoft.flutter.backgroundgeolocation
      #   pluginClass: FLTBackgroundGeolocationPlugin

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.20.0"
dev_dependencies:
  lints: ^2.0.1

